<!--
  Práctica 2 - Fichero 'configuracion.inc'
  Realizado por: Arturo Alonso Carbonero
  Grupo: 3ºA - A1
-->

<?php
  define("DB_DSN", "mysql:host=localhost; dbname=db75936665_pw2021");
  define("DB_USUARIO", "pw75936665");
  define("DB_CONTRASENIA", "75936665");
  define("TAMANIO_PAGINA", 5);
  define("TABLA_USUARIOS", "Usuarios");
  define("TABLA_SECCIONES", "Secciones");
  define("TABLA_ITEMS", "Items");
?>
